# Generated by Django 5.2.10 on 2026-10-02 17:45

import django.db.models.deletion
import filer.fields.file
import filer.fields.folder
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filer", "0018_alter_file_options"),
        ("testapp", "0003_delete_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="testapp.category",
                    ),
                ),
                (
                    "file",
                    filer.fields.file.FilerFileField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="filer.file",
                    ),
                ),
                (
                    "folder",
                    filer.fields.folder.FilerFolderField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="filer.folder",
                    ),
                ),
            ],
        ),
    ]
